### ISSUE TITLE
maven.additionalArguments with url

### ISSUE THREAD

**Issue by pohlmarcus** [whitesource/agents#19]
We don't want to save the Maven Settings file locally, but reference it via URL.
However, with the parameter 
`maven.additionalArguments = -s = https: //url.com/settings.xml `
we have not yet found a way to specify a URL.

Is that possible?

**Comment by annarozin** [comment]
Hi 
Please open a support case.
From which company are you, I'll ask support contact you

**Comment by annarozin** [comment]
closing, should be handled with WhiteSource support
