### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by hasanwhitesource** [whitesource/agents#65]
This issue provides visibility into Renovate updates and their statuses. [Learn more](https://docs.renovatebot.com/key-concepts/dashboard/)

## Pending Approval

These branches will be created by Renovate only once you click their checkbox below.

 - [ ] Update dependency ch.qos.logback:logback-classic to v1.2.10
 - [ ] Update dependency org.apache.maven.plugins:maven-enforcer-plugin to v3.0.0
 - [ ] Update dependency org.apache.maven.plugins:maven-shade-plugin to v2.4.3
 - [ ] Update dependency org.codehaus.mojo:findbugs-maven-plugin to v2.5.5
 - [ ] Update dependency org.codehaus.mojo:jdepend-maven-plugin to v2.0
 - [ ] Update dependency org.freemarker:freemarker to v2.3.31
 - [ ] Update dependency org.mozilla:rhino to v1.7.14
 - [ ] Update dependency org.slf4j:slf4j-api to v1.7.33
 - [ ] Update dependency com.fasterxml.jackson.core:jackson-databind to v2.13.1
 - [ ] Update dependency com.github.github:site-maven-plugin to v0.12
 - [ ] Update dependency commons-codec:commons-codec to v1.15
 - [ ] Update dependency commons-io:commons-io to v2.11.0
 - [ ] Update dependency net.java.dev.jna:jna-platform to v5.10.0
 - [ ] Update dependency org.apache.maven.plugins:maven-checkstyle-plugin to v2.17
 - [ ] Update dependency org.apache.maven.plugins:maven-compiler-plugin to v2.5.1
 - [ ] Update dependency org.apache.maven.plugins:maven-gpg-plugin to v1.6
 - [ ] Update dependency org.apache.maven.plugins:maven-javadoc-plugin to v2.10.4
 - [ ] Update dependency org.apache.maven.plugins:maven-jxr-plugin to v2.5
 - [ ] Update dependency org.apache.maven.plugins:maven-plugin-plugin to v3.6.4
 - [ ] Update dependency org.apache.maven.plugins:maven-project-info-reports-plugin to v2.9
 - [ ] Update dependency org.apache.maven.plugins:maven-site-plugin to v3.10.0
 - [ ] Update dependency org.apache.maven.plugins:maven-source-plugin to v2.4
 - [ ] Update dependency org.apache.maven.plugins:maven-surefire-plugin to v2.22.2
 - [ ] Update dependency org.apache.maven.plugins:maven-surefire-report-plugin to v2.22.2
 - [ ] Update dependency org.codehaus.mojo:cobertura-maven-plugin to v2.7
 - [ ] Update dependency org.mockito:mockito-core to v1.10.19
 - [ ] Update dependency org.whitesource:whitesource-maven-plugin to v3.3.1
 - [ ] Update dependency org.whitesource:wss-agent-parent to v2.10.0
 - [ ] Update dependency org.apache.maven.plugins:maven-checkstyle-plugin to v3
 - [ ] Update dependency org.apache.maven.plugins:maven-compiler-plugin to v3
 - [ ] Update dependency org.apache.maven.plugins:maven-gpg-plugin to v3
 - [ ] Update dependency org.apache.maven.plugins:maven-javadoc-plugin to v3
 - [ ] Update dependency org.apache.maven.plugins:maven-jxr-plugin to v3
 - [ ] Update dependency org.apache.maven.plugins:maven-pmd-plugin to v3
 - [ ] Update dependency org.apache.maven.plugins:maven-project-info-reports-plugin to v3
 - [ ] Update dependency org.apache.maven.plugins:maven-shade-plugin to v3
 - [ ] Update dependency org.apache.maven.plugins:maven-source-plugin to v3
 - [ ] Update dependency org.codehaus.mojo:findbugs-maven-plugin to v3
 - [ ] Update dependency org.mockito:mockito-core to v4
 - [ ] Update dependency org.whitesource:whitesource-maven-plugin to v20
 - [ ] Update dependency org.whitesource:wss-agent-parent to v18

**Comment by nabeelsaabna** [comment]
not relevant
